name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Or your default branch

permissions:
  contents: write # Allow write access to deploy to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Or the version your project uses

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Change to package directory to find docs-requirements.txt
          cd ${{ github.workspace }}
          if [ -f docs-requirements.txt ]; then
            pip install -r docs-requirements.txt;
          else
            # Pin versions to match local development
            pip install 'sphinx>=8.0,<9.0' sphinx-rtd-theme m2r2;
          fi
          # If you have a general requirements.txt, you might still want to install it:
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build Sphinx documentation
        run: |
          cd ${{ github.workspace }}/docs
          sphinx-build -b html . _build/html -v

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/docs/_build/html
          # Optional: specify a custom domain if you have one
          # cname: docs.example.com
